[theme]
font = "sans serif"
baseRadius = "medium"

[theme.light]
primaryColor = "#6b6f3f"
backgroundColor = "#f5f3e4"
secondaryBackgroundColor = "#eae5cc"
textColor = "#1a1a12"

[theme.dark]
primaryColor = "#b5b573"
backgroundColor = "#1c1c14"
secondaryBackgroundColor = "#2a2a1e"
textColor = "#f5f3e4"
